Remove rails-erb-loader which causing to fail on AWS EC2
- Remove pagy.js.erb file who initiates Pagy on JS
- Enable Spring when using webpacker:compile command on travis.yml file

From eb-activity.log file
---
ERROR in ./app/javascript/packs/hello_erb.js.erb
Module build failed (from ./node_modules/rails-erb-loader/index.js):
Error: rails-erb-loader failed with code: 1
    at ChildProcess.<anonymous> (/var/app/ondeck/node_modules/rails-erb-loader/index.js:128:16)
    at ChildProcess.emit (events.js:193:13)
    at maybeClose (internal/child_process.js:999:16)
    at Socket.stream.socket.on (internal/child_process.js:403:11)
    at Socket.emit (events.js:193:13)
    at Pipe._handle.close (net.js:614:12)

ERROR in ./app/javascript/lib/pagy.js.erb
Module build failed (from ./node_modules/rails-erb-loader/index.js):
Error: rails-erb-loader failed with code: 1
    at ChildProcess.<anonymous> (/var/app/ondeck/node_modules/rails-erb-loader/index.js:128:16)
    at ChildProcess.emit (events.js:193:13)
    at maybeClose (internal/child_process.js:999:16)
    at Socket.stream.socket.on (internal/child_process.js:403:11)
    at Socket.emit (events.js:193:13)
    at Pipe._handle.close (net.js:614:12)

https://github.com/usabilityhub/rails-erb-loader/issues/63
https://github.com/rails/webpacker/issues/1560
https://github.com/rails/webpacker/issues/1529